# This workflow auto-approves pull-requests when the github actor is a
# dependabot user and it is opening a new pull request.
#
# The problem that this workflow solves is that we have branch protection on
# our repositories that prevent PRs from merging unless there is an
# approval present. The problem is that this will block PRs that dependabot
# may want to merge automatically. Auto-approving dependabot PRs will allow
# the automatic merge to complete. We control what gets automerged through
# the dependabot configuration.
#
# This is a known issue: https://github.com/dependabot/feedback/issues/852
name: Auto-approve dependabot pull requests
on:
  pull_request:
    types: [opened]

jobs:
  dependabot-triage:
    runs-on: ubuntu-latest
    if: (github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]')

    steps:
      - name: Auto-approve for dependabot
        uses: hmarr/auto-approve-action@v2.0.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
